server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306 #url
    username: root  #用户名
    password: lhc1998.  #密码
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    lettuce:
      shutdown-timeout: 5000