server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: lhc1998.
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    lettuce:
      shutdown-timeout: 5000
      pool:
        max-wait: -1
        max-idle: 20
        min-idle: 2